create table "public"."deffs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null
);

alter table "public"."deffs" enable row level security;

CREATE UNIQUE INDEX deffs_pkey ON public.deffs USING btree (id);

alter table "public"."deffs" add constraint "deffs_pkey" PRIMARY KEY using index "deffs_pkey";
