name: Deploy Migrations to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: cscumtuuhusjobivhfod

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.61.1

      - run: supabase link --project-ref $STAGING_PROJECT_ID
      - run: supabase db push
      - run: supabase functions deploy hello_world --project-ref $STAGING_PROJECT_ID
